# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |test|
  test.vm.box_check_update = "false"
  test.vm.provider "virtualbox" do |vb|
    v.gui = true
    v.memory = 1024
    v.cpus = 2
  end

  test.vm.define "vm-testenv" do ||
    vm-testenv.vm.hostname = "mwiws01"
    vm-testenv.vm.box = "geerlingguy/centos7"
    vm-testenv.vm.network :private_network, ip: "192.168.56.0"
    vm-testenv.vm.network "forwarded_port", guest: "80", host: "8080"

    #Provision the webserver with Ansible
    vm-testenv.vm.provision "ansible_local" do |ansible|
      ansible.playbook="provisioning/playbook.yaml"
      ansible.verbose="true"
    end
  end
 end
