- name: Install dependencies for Homebrew
  apt:
    name:
      - build-essential
      - procps
      - curl
      - file
      - git
    update_cache: yes

- name: Download and run the Homebrew installer
  ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: "{{ username }}/.linuxbrew/bin/brew"
  become: false

- name: Set environment variables for the current session (linuxbrew)
  ansible.builtin.shell: eval "$({{ username }}/.linuxbrew/bin/brew shellenv)"

- name: Set environment variables for the current session (/home/linuxbrew/.linuxbrew)
  ansible.builtin.shell: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

- name: Add Homebrew to zshrc
  ansible.builtin.lineinfile:
    path: "{{ username }}/.zshrc"
    line: 'eval "$($(brew --prefix)/{{ username }}/.linuxbrew/bin/brew shellenv)"'
    create: yes

- name: Ensure brew command is available
  ansible.builtin.shell: echo 'export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"' >> {{ username }}/.zshrc
  args:
    executable: /bin/bash

- name: Check if Homebrew is installed
  ansible.builtin.stat:
    path: /usr/local/bin/brew
  register: brew_installed

- name: Install Homebrew
  ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: not brew_installed.stat.exists
  become: false

- name: Set environment for Homebrew tasks
  ansible.builtin.set_fact:
    ansible_env:
      PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"
  tags: always

- name: Install git-delta
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - git-delta
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"
  become: false

- name: Copy .gitconfig file
  copy:
    src: ./files/.gitconfig
    dest: /home/{{ username }}/.gitconfig
