- name: Ensure KREW_ROOT directory exists
  ansible.builtin.file:
    path: "{{ username }}/.krew"
    state: directory
    mode: '0755'

- name: Ensure TMPDIR directory exists
  ansible.builtin.file:
    path: "{{ username }}/tmp"
    state: directory
    mode: '0755'

- name: Set KREW_ROOT in .zshrc
  ansible.builtin.lineinfile:
    path: "{{ username }}/.zshrc"
    line: 'export KREW_ROOT="{{ username }}/.krew"'
    create: yes

- name: Set TMPDIR in .zshrc
  ansible.builtin.lineinfile:
    path: "{{ username }}/.zshrc"
    line: 'export TMPDIR="{{ username }}/tmp"'
    create: yes

- name: Create KREW_ROOT and TMPDIR directories if not exists
  ansible.builtin.lineinfile:
    path: "{{ username }}/.zshrc"
    insertafter: EOF
    line: |
      mkdir -p "${KREW_ROOT}"
      mkdir -p "${TMPDIR}"

- name: Fetch Krew
  ansible.builtin.get_url:
    url: "https://github.com/kubernetes-sigs/krew/releases/download/{{ krew_version }}/krew-linux_amd64.tar.gz"
    dest: /tmp/krew.tar.gz
    mode: '0755'
  
- name: Make tempdir
  ansible.builtin.file:
    path: "/tmp/krew"
    state: directory
    mode: '0755'

- name: Unarchive krew
  ansible.builtin.unarchive:
    src: /tmp/krew.tar.gz
    dest: /tmp/krew
    remote_src: true

- name: Copy krew plugin to /usr/local/bin
  ansible.builtin.copy:
    src: "/tmp/krew/krew-linux_amd64"
    dest: /usr/local/bin/krew
    mode: '0755'
    remote_src: true

- name: Install krew plugins
  ansible.builtin.command: "krew install {{ item }}"
  register: krew_install_result
  changed_when: "'Installing...' in krew_install_result.stdout"
  become: false
  loop: "{{ krew_plugins }}"
  when: krew_plugins is defined