- name: Download the k3s installation script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s_install.sh
    mode: '0755'

- name: Execute the k3s installation script
  command: /tmp/k3s_install.sh

- name: Change permissions of kubeconfig file
  file:
    path: /etc/rancher/k3s/k3s.yaml
    mode: '0644'

- name: Change owner of kubectl
  file:
    path: /usr/local/bin/kubectl
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'

- name: Make kubectl executable
  file:
    path: /usr/local/bin/kubectl
    mode: '0755'

- name: Change owner of kubectl
  file:
    path: /usr/local/bin/kubectl
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'

- name: Make kubectl executable
  file:
    path: /usr/local/bin/kubectl
    mode: '0755'

- name: Ensure .kube directory exists
  ansible.builtin.file:
    path: "/home/{{ username }}/.kube"  # Adjusted the path and added missing home directory part
    state: directory
    mode: '0755'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy k3s.yaml to user's kube config
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "/home/{{ username }}/.kube/config"  # Adjusted the destination path to include the home directory
    remote_src: yes
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Ensure user owns the kube config file
  ansible.builtin.file:
    path: "/home/{{ username }}/.kube/config"  # Adjusted the path to include the home directory
    state: file
    owner: "{{ username }}"
    group: "{{ username }}"
