- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Download Go binary
  get_url:
    url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
    dest: /tmp/go{{ go_version }}.linux-amd64.tar.gz
    mode: '0755'

- name: Extract Go tarball to /usr/local
  ansible.builtin.unarchive:
    src: /tmp/go{{ go_version }}.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: true
    extra_opts: ["--strip-components=1"]

- name: Ensure ~/.profile exists
  file:
    path: /home/{{ username }}/.profile
    state: touch
    owner: "{{ username }}"
    group: "{{ username }}"
  become: false

- name: Set Go environment variable in ~/.profile
  lineinfile:
    path: /home/{{ username }}/.profile
    line: "{{ item }}"
    create: true
  with_items:
    - 'export GOROOT=/usr/local/go{{ go_version }}'
    - 'export GOPATH=$HOME/go'
    - 'export PATH=$PATH:$GOROOT/bin:$GOPATH/bin'
  become: false

- name: Install kubecolor via go
  ansible.builtin.shell:
    cmd: go install github.com/kubecolor/kubecolor@latest
  become: false

- name: Add PATH export to .zshrc
  ansible.builtin.lineinfile:
    path: /home/{{ username }}/.zshrc
    line: 'export PATH=$PATH:/home/{{ username }}/go/bin'
    state: present