- name: zsh
  ansible.builtin.include_tasks: "zsh.yml"

- name: kubecolor
  ansible.builtin.include_tasks: "kubecolor.yml"
  when: kubecolor_install is defined

- name: terraform
  ansible.builtin.include_tasks: "terraform.yml"
  when: terraform_install is defined

- name: docker
  ansible.builtin.include_tasks: "docker.yml"
  when: docker_install is defined

- name: helm
  ansible.builtin.include_tasks: "helm.yml"
  when: helm_install is defined

- name: kubectl
  ansible.builtin.include_tasks: "kubectl.yml"
  when: kubectl_install is defined

- name: yq
  ansible.builtin.include_tasks: "yq.yml"
  when: yq_install is defined

- name: kubectx-fzf
  ansible.builtin.include_tasks: "kubectx-fzf.yml"
  when: kubectx_fzf_install is defined

- name: krew
  ansible.builtin.include_tasks: "krew.yml"
  when: krew_install is defined