- name: Add hashicorp apt repository key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
    keyring: /etc/apt/trusted.gpg.d/hashicorp.gpg

- name: Add hashicorp apt repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/hashicorp.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    filename: terraform

- name: Install terraform
  ansible.builtin.apt:
    state: present
    pkg: terraform