- name: Download Terraform binary
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: "/tmp/terraform.zip"
  register: download_result
  ignore_errors: yes

- name: Unzip Terraform binary
  ansible.builtin.unarchive:
    src: "/tmp/terraform.zip"
    dest: "/usr/local/bin/"
    remote_src: yes
  when: download_result is success
