- name: (CentOS) Install zsh
  dnf:
    name:
      - zsh
      - git
      - curl
    state: present
    update_cache: yes
  when:
    - ansible_pkg_mgr == "dnf"

- name: (Ubuntu) Install zsh, git, curl
  apt:
    name:
      - zsh
      - git
      - curl
    state: present
    update_cache: yes
  when:
    - ansible_pkg_mgr == "apt"

- name: Change default shell (relog needed)
  command: chsh -s /usr/bin/zsh

- name: Download and install oh-my-zsh framework
  command: 'git clone -c core.autocrlf=input --depth=1 https://github.com/robbyrussell/oh-my-zsh.git .oh-my-zsh'
  become: true
  become_user: '{{ username }}'
  args:
    chdir: '~{{ username }}'
    creates: '~{{ username }}/.oh-my-zsh'
#   register: command_output
# - debug:
#     var: command_output.stdout_lines

- name: Download autosuggestion
  command: 'git clone -c core.autocrlf=input --depth=1 https://github.com/zsh-users/zsh-autosuggestions.git .zsh-autosuggestions'
  args:
    chdir: '~{{ username }}'
    creates: '~{{ username }}/.zsh-autosuggestions'

# git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# - name: Download autosuggestion
#   shell: 'git clone https://github.com/zsh-users/zsh-autosuggestions ${~{{ username }}/.oh-my-zsh/custom:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions'
#   # args:
#   #   chdir: '~{{ username }}'
#   #   creates: '~{{ username }}/.zsh-autosuggestions'
