---
# TODO: Make that this pre_task will not always go into a "changed state"
- name: VirtualBox | Nested virtualilization check
  ansible.builtin.command: cat /proc/cpuinfo
  register: cpuinfo
  failed_when: cpuinfo.stdout.find('svm') == -1 and cpuinfo.stdout.find('vmx') == -1
- name: VirtualBox | Search for 'svm/vmx' in cpuinfo
  debug:
    msg: "{% if 'svm' in cpuinfo.stdout %}svm found{% else %}vmx found{% endif %}"

- name: VirtualBox | Ensure RPM GPG key is present
  rpm_key:
    key: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present

- name: VirtualBox | Ensure YUM repository file exists
  yum_repository:
    name: virtualbox
    description: VirtualBox Repository
    file: virtualbox
    # TODO: Make distro, releaseversion and arch as a variable
    # See https://github.com/PyratLabs/ansible-role-virtualbox/blob/master/tasks/redhat/install-virtualbox.yml
    baseurl: http://download.virtualbox.org/virtualbox/rpm/el/8/x86_64/
    state: present
    enabled: true
    gpgcheck: true
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc

- name: VirtualBox | Ensure VirtualBox is installed (YUM)
  yum:
    # TODO: Make this as a variable
    name: "VirtualBox-6.1"
    state: present
    update_cache: true
  when: ansible_pkg_mgr == "yum"

- name: VirtualBox | Ensure VirtualBox is installed (DNF)
  become: true
  dnf:
    name: "VirtualBox-6.1"
    state: present
    update_cache: true
  when: ansible_pkg_mgr == "dnf"
