class VagrantPlugins::ProviderVirtualBox::Action::Network
  def dhcp_server_matches_config?(dhcp_server, config)
    true
  end
end

Vagrant.configure("2") do |config|
  config.vm.box = "alvistack/centos-9-stream"

  # config.vm.provider "virtualbox" do |v|
  #  v.memory = 1024
  #  v.cpus = 2
  # end

  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "alvistack/centos-9-stream"
    vm1.vm.hostname = "vm1"
    vm1.vm.box_url = "alvistack/centos-9-stream"
    vm1.vm.network "private_network", type: "dhcp"
  end
end
